config/routes.rb
Cse532SocialNetwork::Application.routes.draw do

  resources :preferences

  get "summary/transaction"
  get "summary/stat"
	get "summary/search"
	post "summary/query"

  get "purchase/index"
  get "purchase/history"
  get "purchase/new"
  post "purchase/create"

  get "/management/new"
  post "/management/create"
  get "/management/destroy"
  get "/management/index"

  match '/management/login' => 'management#new'
	match '/management/logout' => 'management#destroy'
	match '/signup' => 'users#new'

  resources :sales

  resources :advertisements

  resources :message_receivers

  resources :messages

  resources :group_requests

  resources :comments

  resources :group_members

  resources :groups

	controller :groups do
		get 'groupsearch' => :search
	end

  resources :posts

  resources :pages

	controller :sessions do
		get 'login' => :new
		post 'login' => :create
		delete 'logout' => :destroy
		get 'logout' => :destroy
	end

  resources :circle_members

  resources :circles

  resources :friends

  resources :friend_requests

  resources :users

  root :to => "users#index"

end

app/models/group.rb
class Group < ActiveRecord::Base
	belongs_to :user
	has_many :group_members, :dependent => :destroy
	has_many :group_requests, :dependent => :destroy

	def before_destroy
		@pages = Page.where(:category => 'group', :owner => id)
		puts "******************* " + @pages.length.to_s
		@pages.each do |p|
			p.destory
		end
	end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json
  def index
     # @groups = Group.find_by_sql("SELECT groups.* from groups, group_members WHERE groups.user_id = #{session[:user_id]} or id in (SELECT group_id FROM group_members WHERE user_id = #{session[:user_id]})")

		@groups = Group.find_by_sql("SELECT g.*, gm.moderator FROM groups AS g, group_members AS gm WHERE g.id = gm.group_id AND gm.user_id = #{session[:user_id]}")

		@groups.each do |g|
			puts g.moderator
			puts g.moderator.class
		end

		# Bug here
		@group_request = GroupRequest.new
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])
		@page = Page.find_by_sql("SELECT * FROM pages WHERE category = 'group' AND owner = #{@group.id}")[0]
    respond_to do |format|
			format.html { redirect_to "/pages/#{@page.id}" }
      format.json { render :json => @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])

		if GroupMember.find_by_sql("SELECT * from group_members WHERE group_id = #{@group.id} AND user_id = #{session[:user_id]} LIMIT 1")[0].moderator
			session[:moderator] = true
		else
			session[:moderator] = false
		end

		@group_members = GroupMember.find_by_sql("SELECT group_members.*, users.first_name, users.last_name FROM group_members, users WHERE group_members.group_id = #{@group.id} AND group_members.user_id = users.id")
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])
		@group.user_id = session[:user_id]

    respond_to do |format|
      if @group.save

				@page = Page.create(:owner => @group.id, :category => 'group')
				@group_member = GroupMember.create(:group_id => @group.id, :user_id => session[:user_id], :moderator => true)
        format.html { redirect_to groups_url, :notice => 'Group was successfully created.' }
        format.json { render :json => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "new" }
        format.json { render :json => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, :notice => 'Group was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
		@pages = Page.where(:category => 'group', :owner => @group.id)
		@pages.each do |p|
			p.destroy
		end
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :ok }
    end
  end

	# GET /groupsearch
	def search
		@groups = []
		if params[:name] and params[:name].length > 0
			@groups = Group.find_by_sql("SELECT * from groups WHERE user_id != '#{session[:user_id]}' AND name = '#{params[:name]}' AND id NOT IN (SELECT group_id FROM group_members WHERE user_id = #{session[:user_id]})")
		else
			@groups = Group.find_by_sql("SELECT * from groups WHERE user_id != '#{session[:user_id]}' AND id NOT IN (SELECT group_id FROM group_members WHERE user_id = #{session[:user_id]})")
		end
		@group_request = GroupRequest.new
		render
	end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  -if @group.errors.any?
    #error_explanation
      %h2= "#{pluralize(@group.errors.count, "error")} prohibited this group from being saved:"
      %ul
        - @group.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.text_field :name, :size => 20, :placeholder => 'Group Name'
    = f.submit 'Create'

app/views/groups/_group.html.haml
.aGroup
	%b= link_to group.name, group

	- if group.user_id == session[:user_id]
		%li= link_to 'Destory', group, :confirm => 'Are you sure?', :method => :delete
	- if group.moderator == 't' or group.moderator == 1
		%li= link_to 'Request', group_requests_url + "?group_id=#{group.id}"
		%li= link_to 'Edit', edit_group_path(group)

app/views/groups/edit.html.haml
= render 'layouts/header'
= render 'layouts/left_bar'

#mainBar
	%h2 Edit group
	= link_to 'Go Back', '/groups'
	%br
	- if @group.user_id == session[:user_id]
		= form_for @group do |f|
			.field
				= f.text_field :name, :size => 15, :value => @group.name
				= f.submit 'Update Group Name'

	.memberList
		- @group_members.each do |m|
			.aGroupMember
				%p= m.first_name + " " + m.last_name
				%ul
					- if @group.user_id == m.user_id
						%p Host
					- elsif @group.user_id == session[:user_id]
						- if m.moderator == true
							= link_to 'Del as Moderator', m, :method => :put, :remote => true, :id => :moderator
						- else
							= link_to 'Set as Moderator', m, :method => :put, :remote => true, :id => :moderator
					- if @group.user_id != m.user_id and m.user_id != session[:user_id] and session[:moderator]
						= link_to 'Remove', m, :method => :delete, :remote => true

app/views/groups/index.html.haml
= render 'layouts/header'
= render 'layouts/left_bar'

#mainBar
	.groupHeader
		%h2 Groups
		= link_to 'Create Group', '/groups/new'
		\|
		= link_to 'Find Group', '/groupsearch'

	.groupList
		= render @groups

app/views/groups/new.html.haml
= render 'layouts/header'
= render 'layouts/left_bar'

#mainBar
	%h2 Create New group
	= render 'form'

app/views/groups/search.html.haml
= render 'layouts/header'
= render 'layouts/left_bar'

#mainBar
	.groupSearchHeader
		%h3 Search Group
		= form_tag('/groupsearch', :method => :get) do
			= text_field_tag :name, nil, :placeholder => 'Group Name', :size => 20
			= submit_tag 'search'
	
	- if @groups.length > 0
		%h3 Groups you may have interest

	- @groups.each do |g|
		.aGroup
			%b= g.name
			= form_for(@group_request, :remote => true) do |form|
				= hidden_field_tag :group_id, g.id
				= form.submit 'Join'

app/views/groups/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @group.name
%p
  %b User:
  = @group.user_id

= link_to 'Edit', edit_group_path(@group)
\|
= link_to 'Back', groups_path