config/routes.rb
Cse532SocialNetwork::Application.routes.draw do

  resources :preferences

  get "summary/transaction"
  get "summary/stat"
	get "summary/search"
	post "summary/query"

  get "purchase/index"
  get "purchase/history"
  get "purchase/new"
  post "purchase/create"

  get "/management/new"
  post "/management/create"
  get "/management/destroy"
  get "/management/index"

  match '/management/login' => 'management#new'
	match '/management/logout' => 'management#destroy'
	match '/signup' => 'users#new'

  resources :sales

  resources :advertisements

  resources :message_receivers

  resources :messages

  resources :group_requests

  resources :comments

  resources :group_members

  resources :groups

	controller :groups do
		get 'groupsearch' => :search
	end

  resources :posts

  resources :pages

	controller :sessions do
		get 'login' => :new
		post 'login' => :create
		delete 'logout' => :destroy
		get 'logout' => :destroy
	end

  resources :circle_members

  resources :circles

  resources :friends

  resources :friend_requests

  resources :users

  root :to => "users#index"

end

app/models/friend_request.rb
class FriendRequest < ActiveRecord::Base
	belongs_to :user
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  # GET /friend_requests
  # GET /friend_requests.json
  def index
		@friend_requests = FriendRequest.find_by_sql("SELECT friend_requests.id, users.first_name, users.last_name FROM friend_requests, users WHERE friend_requests.user_id = #{session[:user_id]} and users.id = friend_requests.requester_id");


    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @friend_requests }
    end
  end

  # GET /friend_requests/1
  # GET /friend_requests/1.json
  def show
    @friend_request = FriendRequest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @friend_request }
    end
  end

  # GET /friend_requests/new
  # GET /friend_requests/new.json
  def new
    @friend_request = FriendRequest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @friend_request }
    end
  end

  # GET /friend_requests/1/edit
  def edit
    @friend_request = FriendRequest.find(params[:id])
  end

  # POST /friend_requests
  # POST /friend_requests.json
  def create
		@friend_request = FriendRequest.new
		@friend_request.user_id = params[:requester_id]
		@friend_request.requester_id = session[:user_id]

    respond_to do |format|
      if FriendRequest.find_by_sql("SELECT count(*) as count FROM friend_requests WHERE user_id = #{params[:requester_id]} AND requester_id = #{session[:user_id]}")[0].count == 0
				@friend_request.save
				format.html { redirect_to users_path, :notice => 'Friend request was successfully sent.' }
				format.js
        format.json { render :json => @friend_request, :status => :created, :location => @friend_request }
      else
        format.html { render :action => "new" }
				format.js
        format.json { render :json => @friend_request.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /friend_requests/1
  # PUT /friend_requests/1.json
  def update
    @friend_request = FriendRequest.find(params[:id])

    respond_to do |format|
      if @friend_request
				tmp = FriendRequest.find_by_sql("SELECT * FROM friend_requests WHERE user_id = #{@friend_request.requester_id} and requester_id = #{@friend_request.user_id} LIMIT 1")
				Friend.create(:user_id => session[:user_id], :fu_id => @friend_request.requester_id)
				Friend.create(:user_id => @friend_request.requester_id, :fu_id => session[:user_id])

				@friend_request.destroy
				tmp[0].destroy if tmp.length > 0

        format.html { redirect_to friend_requests_url, :notice => 'Friend request was successfully updated.' }
				format.js
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @friend_request.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /friend_requests/1
  # DELETE /friend_requests/1.json
  def destroy
    @friend_request = FriendRequest.find(params[:id])
    @friend_request.destroy

    respond_to do |format|
      format.html { redirect_to friend_requests_url }
			format.js
      format.json { head :ok }
    end
  end
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/views/friend_requests/_form.html.haml
= form_for @friend_request do |f|
  -if @friend_request.errors.any?
    #error_explanation
      %h2= "#{pluralize(@friend_request.errors.count, "error")} prohibited this friend_request from being saved:"
      %ul
        - @friend_request.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :requester_id
    = f.number_field :requester_id
  .actions
    = f.submit 'Save'

app/views/friend_requests/_friend_request.html.haml
.aFriendRequest
	%b= friend_request.first_name + " " + friend_request.last_name
	= link_to 'Accept', friend_request, :method => :put, :remote => true
	= link_to 'Ignore', friend_request, :confirm => 'Are you sure?', :method => :delete, :remote => true

app/views/friend_requests/create.js.erb
$('.aUser').bind('ajax:success', function(){
	$(this).fadeOut();
})

app/views/friend_requests/destroy.js.erb
$('.aFriendRequest').bind('ajax:success', function(){
	$(this).fadeOut();
})

app/views/friend_requests/edit.html.haml
%h1 Editing friend_request

= render 'form'

= link_to 'Show', @friend_request
\|
= link_to 'Back', friend_requests_path

app/views/friend_requests/index.html.haml
= render 'layouts/header'
= render 'layouts/left_bar'

#mainBar
	.friendRequestHeader
		%h2 Friend Requests

	.friendRequestList
		- if @friend_requests.length == 0
			%p No new requests
		- else
			= render @friend_requests

app/views/friend_requests/new.html.haml
%h1 New friend_request

= render 'form'

= link_to 'Back', friend_requests_path

app/views/friend_requests/show.html.haml
%p#notice= notice

%p
  %b User:
  = @friend_request.user_id
%p
  %b Requester:
  = @friend_request.requester_id

= link_to 'Edit', edit_friend_request_path(@friend_request)
\|
= link_to 'Back', friend_requests_path

app/views/friend_requests/update.js.erb
$('.aFriendRequest').bind('ajax:success', function(){
	$(this).fadeOut();
})