config/routes.rb
Cse532SocialNetwork::Application.routes.draw do

  resources :preferences

  get "summary/transaction"
  get "summary/stat"
	get "summary/search"
	post "summary/query"

  get "purchase/index"
  get "purchase/history"
  get "purchase/new"
  post "purchase/create"

  get "/management/new"
  post "/management/create"
  get "/management/destroy"
  get "/management/index"

  match '/management/login' => 'management#new'
	match '/management/logout' => 'management#destroy'
	match '/signup' => 'users#new'

  resources :sales

  resources :advertisements

  resources :message_receivers

  resources :messages

  resources :group_requests

  resources :comments

  resources :group_members

  resources :groups

	controller :groups do
		get 'groupsearch' => :search
	end

  resources :posts

  resources :pages

	controller :sessions do
		get 'login' => :new
		post 'login' => :create
		delete 'logout' => :destroy
		get 'logout' => :destroy
	end

  resources :circle_members

  resources :circles

  resources :friends

  resources :friend_requests

  resources :users

  root :to => "users#index"

end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
	validates :category, :company, :item_name, :unit_price, :quantity, :presence => true
	validates :unit_price, :numericality => {:greater_than => 0.0}
	validates :quantity, :numericality => {:greater_than_or_equal_to => 0}

	has_many :sales
end

app/models/circle.rb
class Circle < ActiveRecord::Base
	belongs_to :user
	has_many :circle_members, :dependent => :destroy
end

app/models/circle_member.rb
class CircleMember < ActiveRecord::Base
	belongs_to :circle
	belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
end

app/models/friend.rb
class Friend < ActiveRecord::Base
	belongs_to :user
end

app/models/friend_request.rb
class FriendRequest < ActiveRecord::Base
	belongs_to :user
end

app/models/group.rb
class Group < ActiveRecord::Base
	belongs_to :user
	has_many :group_members, :dependent => :destroy
	has_many :group_requests, :dependent => :destroy

	def before_destroy
		@pages = Page.where(:category => 'group', :owner => id)
		puts "******************* " + @pages.length.to_s
		@pages.each do |p|
			p.destory
		end
	end
end

app/models/group_member.rb
class GroupMember < ActiveRecord::Base
	belongs_to :group
	belongs_to :user
end

app/models/group_request.rb
class GroupRequest < ActiveRecord::Base
	belongs_to :group
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user
	has_many :message_receivers, :dependent => :destroy
end

app/models/message_receiver.rb
class MessageReceiver < ActiveRecord::Base
	belongs_to :message
	belongs_to :user
end

app/models/page.rb
class Page < ActiveRecord::Base
	has_many :posts, :dependent => :destroy

	validates :category, :presence => true
	validates :category, :inclusion => { :in => %w(user group), :message => "%{value} is not a valid value" }
	validates :owner, :presence => true
	validate :check_in_user_or_group

	private

	def check_in_user_or_group
		if category == 'user'
			errors.add(:category, 'No such user') unless User.find_by_id(owner)
		end
		if category == 'group'
			errors.add(:category, 'No such group') unless Group.find_by_id(owner)
		end
	end
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	belongs_to :page
	has_many :comments, :dependent => :destroy

	# validations
	validates :user_id, :page_id, :content, :presence => true
end

app/models/preference.rb
class Preference < ActiveRecord::Base
	belongs_to :user
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	belongs_to :user
	belongs_to :advertisement

end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base
	# Dependencies
	has_many :friends, :dependent => :destroy
	has_many :friend_requests, :dependent => :destroy
	has_many :circles, :dependent => :destroy
	has_many :circle_members, :dependent => :destroy
	has_many :groups, :dependent => :destroy
	has_many :group_members, :dependent => :destroy
	has_many :group_requests, :dependent => :destroy
	has_many :posts, :dependent => :destroy
	has_many :comments, :dependent => :destroy
	has_many :messages, :dependent => :destroy
	has_many :sales
	has_many :preferences, :dependent => :destroy
	has_many :message_receivers, :dependent => :destroy

	# Validations
	validates :first_name, :presence => true
	validates :last_name, :presence => true

	# Email
	validates :email, :presence => true, :uniqueness => true
	validates :email, :format => { :with => /[_a-z0-9]+(\.[_a-z0-9]+)*@[a-z0-9]+(\.[a-z0-9]+)*(\.[a-z]{2,4})/, :message => "%{value} is not a valid email address" }
	validates :email, :confirmation => true, :unless => Proc.new { |a| a.id != nil }
	# validates :email_confirmation, :presence => true

	validates :password, :confirmation => true
	attr_accessor :password_confirmation
	attr_reader :password
	validate :password_must_be_present

	def before_destroy
		@pages = Page.where(:category => 'user', :owner => id)
		@pages.each do |p|
			p.destroy
		end
	end

	def password=(password)
		@password = password
		if password.present?
			generate_salt
			self.hashed_password = self.class.encrypt_password(password, salt)
		end
	end

	def User.authenticate(email, password)
		# puts "*******************************" + password
		if email == "" or password == ""
			return nil
		end
		if user = find_by_email(email) and user.hashed_password == encrypt_password(password, user.salt)
			user
		else
			return nil
		end
	end

	def User.encrypt_password(password, salt)
		Digest::SHA2.hexdigest(password + "wibble" + salt)
	end

	private

	def password_must_be_present
		errors.add(:password, "Missing password") unless hashed_password.present?
	end

	def generate_salt
		self.salt = self.object_id.to_s + rand.to_s
	end

end

app/controllers/message_receivers_controller.rb
class MessageReceiversController < ApplicationController
  # GET /message_receivers
  # GET /message_receivers.json
  def index
    @message_receivers = []

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @message_receivers }
    end
  end

  # GET /message_receivers/1
  # GET /message_receivers/1.json
  def show
    @message_receiver = MessageReceiver.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @message_receiver }
    end
  end

  # GET /message_receivers/new
  # GET /message_receivers/new.json
  def new
    @message_receiver = MessageReceiver.new
		@friends = Friend.find_by_sql("SELECT friends.*, users.first_name, users.last_name FROM friends, users WHERE friends.user_id = #{session[:user_id]} AND friends.fu_id = users.id")
		session[:receivers] = []

    respond_to do |format|
      format.html # new.html.erb
			format.js
      format.json { render :json => @message_receiver }
    end
  end

  # GET /message_receivers/1/edit
  def edit
    @message_receiver = MessageReceiver.find(params[:id])
  end

  # POST /message_receivers
  # POST /message_receivers.json
  def create
    @message_receiver = MessageReceiver.new

		puts params[:name]
		puts session[:receivers]

		session[:receivers] << params[:fu].to_i

    respond_to do |format|
			format.js
    end
  end

  # PUT /message_receivers/1
  # PUT /message_receivers/1.json
  def update
    @message_receiver = MessageReceiver.find(params[:id])

    respond_to do |format|
      if @message_receiver.update_attributes(params[:message_receiver])
        format.html { redirect_to @message_receiver, :notice => 'Message receiver was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @message_receiver.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /message_receivers/1
  # DELETE /message_receivers/1.json
  def destroy
    @message_receiver = MessageReceiver.find(params[:id])
    @message_receiver.destroy

    respond_to do |format|
      format.html { redirect_to message_receivers_url }
			format.js
      format.json { head :ok }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/message_receivers_helper.rb
module MessageReceiversHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/message_receivers/_create.html.haml
%p
	= params[:name]

app/views/message_receivers/_form.html.haml
= form_for @message_receiver do |f|
  -if @message_receiver.errors.any?
    #error_explanation
      %h2= "#{pluralize(@message_receiver.errors.count, "error")} prohibited this message_receiver from being saved:"
      %ul
        - @message_receiver.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :message_id
    = f.number_field :message_id
  .field
    = f.label :user_id
    = f.number_field :user_id
  .actions
    = f.submit 'Save'

app/views/message_receivers/_new.html.haml
- @friends.each do |f|
	.addReceiver
		%b= f.first_name + " " + f.last_name
		= link_to 'Add', "/message_receivers?fu=#{f.fu_id}&name=#{f.first_name + " " + f.last_name}", :method => :post, :remote => true

app/views/message_receivers/create.js.erb
$(".receiverList1").append("<%= escape_javascript(render 'create') %>");
$(".addReceiver").bind('ajax:success', function() {
		$(this).fadeOut();
});

app/views/message_receivers/destroy.js.erb
$('.aMessage').bind('ajax:success', function(){
	$(this).fadeOut();
});

app/views/message_receivers/edit.html.haml
%h1 Editing message_receiver

= render 'form'

= link_to 'Show', @message_receiver
\|
= link_to 'Back', message_receivers_path

app/views/message_receivers/index.html.haml
%h1 Listing message_receivers

%table
  %tr
    %th Message
    %th User
    %th
    %th
    %th

  - @message_receivers.each do |message_receiver|
    %tr
      %td= message_receiver.message_id
      %td= message_receiver.user_id
      %td= link_to 'Show', message_receiver
      %td= link_to 'Edit', edit_message_receiver_path(message_receiver)
      %td= link_to 'Destroy', message_receiver, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Message receiver', new_message_receiver_path

app/views/message_receivers/new.html.haml
%h1 New message_receiver

= render 'form'

= link_to 'Back', message_receivers_path

app/views/message_receivers/new.js.erb
$('.receiverList1').html('');
$('.receiverList2').html('<%= escape_javascript(render 'new') %>');

app/views/message_receivers/show.html.haml
%p#notice= notice

%p
  %b Message:
  = @message_receiver.message_id
%p
  %b User:
  = @message_receiver.user_id

= link_to 'Edit', edit_message_receiver_path(@message_receiver)
\|
= link_to 'Back', message_receivers_path